# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TableVIewReactorKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TableVIewReactorKit
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'ReactorKit'
  pod 'RxViewController'
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'ReusableKit/RxSwift'
  pod 'RxDataSources', '~> 4.0'

end
